---

- name: Add Grafana repository key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana repository
  apt_repository:
    repo: "deb https://packages.grafana.com/enterprise/deb stable main"
    filename: "influxdb"
    state: present

- name: Install Grafana
  apt:
    name: grafana
    update_cache: yes

- name: Start Grafana
  service:
    name: grafana-server
    state: restarted
    enabled: yes
